/**
 * Types of error modal severity levels.
 */
export type ErrorType = 'error' | 'warning' | 'alert' | 'info';

/**
 * Complete configuration for the error modal component.
 *
 * @remarks
 * Generated by ErrorModalService based on error type and user input.
 * Contains all visual and behavioral settings for the modal.
 *
 * @see {@link ErrorModalService}
 */
export interface ErrorModalConfig {
  /**
   * Error severity type.
   */
  type: ErrorType;

  /**
   * Error code for reference.
   *
   * @example "ERR_500"
   */
  code: string;

  /**
   * Main error message.
   */
  message: string;

  /**
   * Additional error details as key-value pairs.
   *
   * @example { "endpoint": "/api/services", "status": "500" }
   */
  details: Record<string, string>;

  /**
   * Text for the action button.
   *
   * @example "Volver al inicio"
   */
  buttonText: string;

  /**
   * Whether to redirect to main page when modal closes.
   */
  redirectToMain: boolean;

  /**
   * CSS classes for the header background.
   */
  headerClass: string;

  /**
   * CSS classes for the icon styling.
   */
  iconClass: string;

  /**
   * CSS classes for the button styling.
   */
  buttonClass: string;

  /**
   * CSS classes for the modal border.
   */
  borderClass: string;
}

/**
 * Partial configuration for creating an error modal.
 *
 * @remarks
 * Users provide minimal information; ErrorModalService fills in defaults based on type.
 */
export type ErrorModalInput = Partial<Omit<ErrorModalConfig, 'type'>>;
