/**
 * QR code data for payment.
 *
 * @remarks
 * Contains the QR image and validity information for bank app scanning.
 */
export interface QRData {
  /**
   * Validity period/expiration of the QR code.
   *
   * @example "2024-03-15T23:59:59"
   */
  validity: string;

  /**
   * Base64-encoded QR code image.
   *
   * @remarks
   * Can be directly used in an <img> tag with src="data:image/png;base64,{qrImage}"
   */
  qrImage: string;
}

/**
 * Payment request structure for cart processing.
 *
 * @remarks
 * Used in ApiService.generateQRcode()
 */
export interface PagoRequest {
  /**
   * Payment method code.
   *
   * @example "QR"
   */
  medioPago: string;

  /**
   * Array of cart items to process.
   */
  itemsCarrito: unknown[];

  /**
   * Total service amount in Bolivianos.
   */
  totalServicios: number;

  /**
   * Total commission amount in Bolivianos.
   */
  totalComisiones: number;

  /**
   * Grand total (services + commissions) in Bolivianos.
   */
  totalGeneral: number;

  /**
   * Document type code.
   *
   * @see {@link DatosFacturacion.tipoDocumento}
   */
  tipoDocumento: number;

  /**
   * Document number (CI or NIT).
   */
  documentoSIN: string;

  /**
   * Document complement (optional extension for CI).
   */
  complementoSIN: string;

  /**
   * Special NIT exception code for tax control.
   *
   * @remarks
   * Values: '99001', '99002', '99003' for "Control Tributario"
   */
  excepcionNIT: string;

  /**
   * Business name or full name for invoice.
   */
  razonSocial: string;

  /**
   * Email address for invoice delivery.
   */
  correoElectronico: string;

  /**
   * Phone number for contact.
   */
  numeroTelefono: string;

  /**
   * Optional browser fingerprint for fraud prevention.
   *
   * @remarks
   * Generated by FingerprintService using FingerprintJS
   */
  browserFingerprint?: string;
}

/**
 * API response for payment processing.
 */
export interface PagoResponse {
  /**
   * Indicates if the payment processing was successful.
   */
  success: boolean;

  /**
   * QR code data for payment.
   */
  data: QRData;
}

/**
 * API response for NIT verification.
 *
 * @remarks
 * Used in checkout wizard to validate billing information.
 */
export interface NITResponse {
  /**
   * Indicates if the verification request was successful.
   */
  success: boolean;

  /**
   * Verification result data.
   */
  data: {
    /**
     * Whether the NIT is valid.
     */
    valid: boolean;

    /**
     * Document status from SIN registry.
     */
    estadoDocumento?: string;

    /**
     * Registered business name (if NIT is valid).
     */
    razonSocial?: string;

    /**
     * Optional message (e.g., error description).
     */
    message?: string;
  };
}
